#!/bin/bash
set -e

# Generated by DeepSeek

if ! nvidia-smi &>/dev/null; then
    echo "Error: nvidia-smi failed to execute" >&2
    exit 1
fi

# Get list of all GPUs and their UUIDs
all_gpus=$(nvidia-smi --query-gpu=index,uuid --format=csv,noheader,nounits | sed 's/, /:/g')

if [ -z "$all_gpus" ]; then
    echo "Error: No NVIDIA GPUs detected" >&2
    exit 2
fi
# Get list of GPUs in use by compute apps
used_gpus=$(nvidia-smi --query-compute-apps=gpu_uuid --format=csv,noheader,nounits 2>/dev/null | sort -u)

# Determine free GPUs
free_gpus=()
while IFS=: read -r index uuid; do
    if ! echo "$used_gpus" | grep -q "$uuid"; then
        free_gpus+=("$index")
    fi
done <<< "$all_gpus"

if [ ${#free_gpus[@]} -gt 0 ]; then
    echo "${free_gpus[*]}"
    exit 0
else
    echo "No free NVIDIA GPUs found." >&2
    echo 255
    exit 0
fi
